- name: Load platform-specific variable file, if present
  include_vars: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_distribution }}.yml"
      skip: true

- name: Add java repo
  apt_repository:
    repo: "{{ apt_java_repo }}"
    state: present
    update_cache: yes
  when: install_java

- name: Accept Oracle license prior JDK installation (select)
  debconf: name={{ apt_java_package }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: install_java
  ignore_errors: "{{ ansible_check_mode }}"

- name: Accept Oracle license prior JDK installation (seen)
  debconf: name={{ apt_java_package }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='seen'
  when: install_java
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Java
  apt: name={{ apt_java_package }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  when: install_java
  ignore_errors: "{{ ansible_check_mode }}"

- name: Update Java security
  lineinfile:
    dest: "/etc/java-8-oracle/security/java.policy"
    regexp: "{{ item | regex_escape() }}"
    line: "        {{ item }}"
    insertbefore: "};"
  with_items: "{{ java_security_policies }}"
